export const SET_COUNTRIES_LOADING_ON = "SET_COUNTRIES_LOADING_ON";
export const SET_COUNTRIES_LOADING_OFF = "SET_COUNTRIES_LOADING_OFF";
export const SET_COUNTRY_DATA = "SET_COUNTRY_DATA";
export const SET_LOCALE = "SET_LOCALE";
export const SET_COUNTRY_NAME = "SET_COUNTRY_NAME";
export const SET_COUNTRIES_DATA = "SET_COUNTRIES_DATA";
export const LOAD_ALL_COUNTRIES = "LOAD_ALL_COUNTRIES";

// load on demand
export const LOAD_COUNTRIES_BY_NAME = "LOAD_COUNTRIES_BY_NAME";
export const SET_AVAILABLE_COUNTRIES = "SET_AVAILABLE_COUNTRIES";
export const SET_CURRENT_COUNTRY = "SET_CURRENT_COUNTRY";
